version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
  postgres-test:
    image: postgres
    restart: always
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - 5433:5432
volumes:
  postgres_data:
  postgres_test_data: