definitions:
  auth.JwtToken:
    properties:
      raw:
        type: string
      signed:
        type: string
    type: object
  auth.RegisterRequestDTO:
    properties:
      birth_date:
        example: "2024-08-15"
        type: string
      cpf:
        example: "32212276723"
        type: string
      email:
        example: john.doe@example.com
        type: string
      name:
        example: John Doe
        type: string
      password:
        example: password123
        type: string
    type: object
  auth.RegisterResponseDTO:
    properties:
      accessToken:
        $ref: '#/definitions/auth.JwtToken'
      user:
        $ref: '#/definitions/auth.RegisterUser'
    type: object
  auth.RegisterUser:
    properties:
      birth_date:
        type: string
      cpf:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  user.CreateUserRequestDTO:
    properties:
      birth_date:
        type: string
      cpf:
        type: string
      email:
        type: string
      name:
        description: '@example {"name": "John Doe", "email": "john.doe@example.com",
          "password": "teste1234", "cpf": "23212332112", "birth_date": "2024-08-12"}'
        type: string
      password:
        type: string
    type: object
  user.CreateUserResponseDTO:
    properties:
      birth_date:
        type: string
      cpf:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  utils.HttpError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is the API for the online Book Reservation service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Book Reservation API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/auth.RegisterRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.RegisterResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HttpError'
      summary: Register a new User
      tags:
      - auth
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User details
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserRequestDTO'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.CreateUserResponseDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.HttpError'
      summary: Create an User
      tags:
      - users
swagger: "2.0"
